<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9">

  <xsl:output method="html" encoding="UTF-8" indent="yes"/>

  <xsl:template match="/">
    <html>
      <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>Sitemap</title>
        <link rel="stylesheet" type="text/css" href="./assets/css/delos.css"/>
        <link rel="stylesheet" type="text/css" href="./assets/css/delos_cont.css"/>
      </head>
      <body>
        <div class="il-layout-page">
          <header>
            <div class="header-inner">
                <h1 class="il-page-content-header media-heading ilHeader">Sitemap</h1>
                <div class="ilHeaderDesc">Generated by SEO plugin for ILIAS.</div>
            </div>
          </header>
          <div class="il-system-infos"></div>
          <div class="nav il-maincontrols"></div>
          <main class="il-layout-page-content">
            <div id="mainspacekeeper" class="container-fluid">
              <div class="row" style="position: relative;">
                <div id="fixed_content" class="ilContentFixed">
                  <div id="mainscrolldiv">
                    <div class="ilTabsContentOuter">
                      <div id="ilContentContainer">
                        <div class="row">
                          <div id="il_center_col" class="col-sm-12">
                            <div class="ilTableOuter">
                              <div class="table-responsive">
                                <table class="table table-striped fullwidth">
                                  <thead>
                                    <tr>
                                      <th><span>URL</span></th>
                                      <th><span>Last Modified</span></th>
                                      <th><span>Change Frequency</span></th>
                                      <th><span>Priority</span></th>
                                    </tr>
                                  </thead>
                                  <tbody>
                                    <xsl:for-each select="//s:url">
                                      <tr class="tblrow2">
                                        <td><a href="{s:loc}"><xsl:value-of select="s:loc"/></a></td>
                                        <td>
                                          <xsl:call-template name="format-date">
                                            <xsl:with-param name="iso" select="s:lastmod"/>
                                          </xsl:call-template>
                                        </td>
                                        <td><xsl:value-of select="s:changefreq"/></td>
                                        <td><xsl:value-of select="s:priority"/></td>
                                      </tr>
                                    </xsl:for-each>
                                  </tbody>
                                </table>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </main>
        </div>
      </body>
    </html>
  </xsl:template>

  <xsl:template name="format-date">
    <xsl:param name="iso"/>

    <!-- Datetime -->
    <xsl:variable name="year" select="substring($iso, 1, 4)"/>
    <xsl:variable name="month" select="substring($iso, 6, 2)"/>
    <xsl:variable name="day" select="substring($iso, 9, 2)"/>
    <xsl:variable name="hour" select="substring($iso, 12, 2)"/>
    <xsl:variable name="min" select="substring($iso, 15, 2)"/>

    <!-- Timezone -->
    <xsl:variable name="tzStart" select="string-length($iso) - 5"/>
    <xsl:variable name="tz" select="substring($iso, $tzStart)"/>

    <!-- Month to name -->
    <xsl:variable name="monthNames" select="'JanFebMarAprMayJunJulAugSepOctNovDec'"/>
    <xsl:variable name="monthName" select="substring($monthNames, (number($month) - 1) * 3 + 1, 3)"/>

    <!-- Formatted date -->
    <xsl:value-of select="concat($day, ' ', $monthName, ' ', $year)"/>
    <xsl:if test="$hour and $min">
      <xsl:value-of select="concat(', ', $hour, ':', $min)"/>
    </xsl:if>
    <xsl:if test="contains($tz, '+') or contains($tz, '-')">
      <xsl:value-of select="concat(' (UTC', $tz, ')')"/>
    </xsl:if>
    <xsl:if test="$tz = 'Z'">
      <xsl:text> (UTC)</xsl:text>
    </xsl:if>
  </xsl:template>
</xsl:stylesheet>